#config jwt
app : 
  name : tmdt_rest
jwt:
  header: Authorization
  secret: mySecret
  prefix: Bearer
  expiration: 600
  mobile_expires_in: 600
  cookie : AUTH-TOKEN
  route:
    authentication:
      path: auth
      refresh: refresh
#config email      
email:
  from: ttlang162@gmail.com

#aes  
aes : 
  key: Bar12345Bar12345
  initVector : RandomInitVector     
  
#front-end
front_end :
  scheme: http
  server_name: localhost
  server_port : 4200
  link_reset_password : "/pages/kich-hoat?key-change="
  link_register : "/pages/kich-hoat?key="
  
#google drive api
google :
  service_account_email : ttlang@ttlang-171013.iam.gserviceaccount.com
  application_name : ttlang
  folder_id : 0B27mfRY62YKZaU9Yby1EdGJ5cjg
  service_account_key : ttlang-f98aaa157b45.p12  
  

#paypal
paypal:
  mode: sandbox
  client:
      app: ATxYEuV1ZntyEvEIdUYk8gzjMrArES481gUUaGCqiD1vgTBziUNJSBwwWUtWTbS5owaTHNQSiMLpYTpi
      secret: ED3cyFA1zIpnzAruyGNrusBRfPxbmT9ZSBT_RbecZS3hdkaODrhPItM0iy0fcYIO7GyUDT-xT_5M8Prn
  success_url : pay/success
  cancle      : pay/cancel 
    